### ISSUE TITLE
Docker Hub image only has :latest tag

### ISSUE THREAD

**Issue by ironicbadger** [m1dnight/exbin#15]
First, thanks for this awesome software!

It's generally considered bad practice to rely on the `:latest`, many articles exist on this topic such as [this one](https://blog.linuxserver.io/2018/04/22/the-dangers-of-pulling-latest/). Is there a chance you could push some versioned image tags to docker hub please? Thanks!

**Comment by m1dnight** [comment]
I have modified the Makefile to tag images with a version number now. Building latest can only be done manually. See 406471e. 

Thanks for this issue!
