### ISSUE TITLE
Default docker-compose.yml database has no persistence

### ISSUE THREAD

**Issue by ironicbadger** [m1dnight/exbin#16]
The `docker-compose.yml` file presented in the repo is a great start but I am worried that the default recommendation has no persistence baked into the example. A bind mount volume or a docker volume included there might prevent folks from accidental data loss.

Furthermore it is not common to use `restart: always` an app that is not critical, using `restart: unless-stopped` is much more common and less presumptuous.

https://github.com/m1dnight/exbin/blob/master/docker-compose.yml#L6

**Comment by m1dnight** [comment]
I've already changed the restart policy of the docker image (ee4805f) but I still need to have a more detailed look into the persistence. My knee-jerk reaction is to add `-v /tmp/pg:/var/lib/postgresql/data` but maybe there is a better way. 

Thanks for the issue!

**Comment by m1dnight** [comment]
I ended up adding a simple volume. If people really want fancier approaches like containers as data (e.g., https://github.com/DanielCaldwell/postgres-docker-persistant-data) they can still modify it to their liking (bb477af)
