### ISSUE TITLE
Default view mode

### ISSUE THREAD

**Issue by ironicbadger** [m1dnight/exbin#18]
We're going to adopt exbin as the primary pastebin for all our listener feedback at Jupiter Broadcasting. At the moment it defaults to syntax highlight mode. Could we ask you to implement an env flag to default to reader mode perhaps?

https://paste.docs.lol

**Comment by m1dnight** [comment]
I've done so in the latest commits. Just set `DEFAULT_VIEW`  to either `code`, `reader`, or `raw`. Any other value will default to `code`. 

I will have a look at the other issue, but I'm having some troubles finding the time. I will handle it though.

**Comment by ironicbadger** [comment]
This is perfect. Thank you!
