### ISSUE TITLE
Moderation / Spam

### ISSUE THREAD

**Issue by ironicbadger** [m1dnight/exbin#20]
How would one delete a paste if it were deemed to be spam on a public instance?

Thanks.

**Comment by m1dnight** [comment]
I've added a master password. Set it using the environment variable `ADMIN_PASSWORD` to something secure. 

When set you can go to the `/login` path. If you login the banner will turn red, if you're not logged in it's the regular color. 

I did not want to add several users, just an admin, I hope that's enough for you. 

Asn admin you can delete/view any snippet through the `/list` path. 

 - Christophe

**Comment by ironicbadger** [comment]
Simply fantastic. Thank you for your time in adding all these requests for us. 

I'll be sure to give your project a hearty recommendation on a future self hosted podcast episode.
