### ISSUE TITLE
Refreshing a snippit page increments the views counter.

### ISSUE THREAD

**Issue by ghost** [m1dnight/exbin#21]
It's possible for a single user to increment the views counter simply by refreshing the page. This skews the stats page's "Most Viewed" and "Average Views" stats.

**Comment by m1dnight** [comment]
HI,

Thanks for your issue.

I was thinking this over and I'm not sure if I want this behavior to 
change. It is pretty difficult to distinguish between a refresh and a 
page request. I could, for example, log the IP  address of each request, 
and if that IP requests the same snippet twice within a certain time 
period it would not increment the counter.

I'm going to have to mull this over a bit more before I know what to do. 
I'll keep you posted.

**Comment by ghost** [comment]
Log a hash of each IP address salted with some additional browser data like the useragent. Optionally purged every adjustable interval. 

This would result in each IP+Browser getting 1 view every 24 hours for example. No cookies required, no plaintext IPs logged, the hashed and salted IPs that are logged would be occasionally purged, and different people presumably using different useragents under the same IP would get to increment their views too.

**Comment by m1dnight** [comment]
Makes sense to me.  I'll work on it asap.

**Comment by m1dnight** [comment]
I've got a working version of this. Just need to integrate it and I'm done.

**Comment by m1dnight** [comment]
I've done an overhaul of exbin and this is now part of it. A snippet will only increment its viewcounter once every 24 hours. A user is identified by means of IP, path, and cookie. Nothing is logged in terms of IP and such.
