### ISSUE TITLE
Searching is case sensitive. 

### ISSUE THREAD

**Issue by ghost** [m1dnight/exbin#22]
Searching is currently case sensitive, for example if a snippet contains the text `Joshua Fern`, searching `josh` will return no results while searching `Josh` will.

**Comment by m1dnight** [comment]
Hi, 
I will definitely work on this, but right now I'm swamped with my dissertation. I will give it some time ASAP.

/ Christophe

**Comment by ghost** [comment]
No worries, take your time.

**Comment by m1dnight** [comment]
I fixed this issue in https://github.com/m1dnight/exbin/commit/b6fb38e82c2f898f1b01d72567e50d88f1017f77. 

It was surprisingly simple: a 1 letter change :D
