### ISSUE TITLE
Utilize External URL property on the About page

### ISSUE THREAD

**Issue by russjr08** [m1dnight/exbin#23]
I noticed that currently there is an `EXTERNAL_URL` parameter in the `docker-compose.yml` file, it would be pretty cool if ExBin could utilize this (or pulled from an environment variable) in the `/about` page.

**Comment by m1dnight** [comment]
Hi, 
I will definitely work on this, but right now I'm swamped with my dissertation. I will give it some time ASAP.

/ Christophe

**Comment by joshproehl** [comment]
Could also include the correct TCP_PORT value
