### ISSUE TITLE
Password protect POST to port 9999

### ISSUE THREAD

**Issue by jordantrizz** [m1dnight/exbin#27]
Would it be possible to protect POST's to port 9999 by passing a header? I personally use exbin as a private Pastebin so no one needs to access it's a public page or the port except for me or someone I want to have access.

**Comment by m1dnight** [comment]
I don't think that's possible given the way it's implemented right now. There is no protocol on port 9999, it's a simple socket that expects bytes.  There is an API to POST to, however.

To protect the TCP socket with a password you would need to either expect a specific byte sequence before your input, or somehow restrict based on IP. 
I can have a look and see if there is something I can do. I expect it to work something like this:

```
$ (echo "thisismypassword" ; echo "this is the content") | nc exbin.call-cc.be 9999
https://exbin.call-cc.be/raw/NebulizingPanagia
```

That way, I can check on the serverside whether or not the first line of the data matches a predefined line (i.e., the password). If it's not, the socket can be aborted and the connection will be dropped. 

The API on the other hand can be secured quite easily with an API token. The trade-off is that it's not super trivial to post to the endpoint using a bash script. Currently, this is how it should be done: 

```
$ curl -X POST -H "Content-Type: application/json" -d '{"content": "thisisthecontent", "private": "true"}' "https://exbin.call-cc.be/api/snippet"
```

I could add a password field to the JSON.

Let me know what you think.
/Christophe

**Comment by jordantrizz** [comment]
Wow Christophe! Thanks for the quick response.

Right, it's simply a socket with bytes! Totally was being silly when I asked about a header. Since it's there's no HTTP protocol you can't set a header.

I think the first option is a good start. I can then wrap it in a bash function

```
exbin { 
(echo "thisismypassword" ; echo $@) | nc exbin.call-cc.be 9999
}
```

**Comment by m1dnight** [comment]
I think I even have the basics for this in place already. Will get back to you asap.

**Comment by jordantrizz** [comment]
Thanks!

**Comment by jordantrizz** [comment]
Oh and no rush on this. I'm just getting random scans on 9999 for some weird reason :)

Oh and right now I'm just getting bots and automated submissions. Any thoughts on password protecting the submissions too?

**Comment by m1dnight** [comment]
I've been mulling this over and I think that a password protected socket is a bit strange. 
From what you have said, you are fine with a bash function to hide the authentication. That implies that you would be fine with a bash function around a `curl` POST too? 
On the other hand, losing the ability to pipe into a netcat command is pretty big sacrifice, so perhaps a prefix is not the worst of ideas after all. 

> Oh and right now I'm just getting bots and automated submissions. Any thoughts on password protecting the submissions too?

I think the easiest fix would be to add some simple auth over nginx right now. Users and authentication is something that's going to take a bit longer, so I won't promise it yet.

**Comment by jordantrizz** [comment]
I'm fine with a curl POST with authentication :)

I've added HTTP auth with Traefik.

Can't wait for the users and authentication :)

**Comment by m1dnight** [comment]
I've added authentication to the API, see the updated documentation.

Notice I also changed the layout a bit. It came with an upgrade to a newer phoenix version. 

The socket authentication is wip.

```
$ curl -H "Content-Type: application/json" -X POST -d '{"content": "the content", "private": "true", "ephemeral": "true", "token": "invalidtoken"}' https://exbin.call-cc.be/api/new 
{"error": "invalid token"}
```

```
$ curl -H "Content-Type: application/json" -X POST -d '{"content": "the content", "private": "true", "ephemeral": "true", "token": "secrettoken"}' https://exbin.call-cc.be/api/new 
{"content":"the content","created":"2021-07-22T14:41:50Z","name":"BilletingDace","url":"http://exbin.call-cc.be:6000/BilletingDace"}
```
