### ISSUE TITLE
Ephemeral documentation and countdown timer is wrong

### ISSUE THREAD

**Issue by Vogete** [m1dnight/exbin#29]
I started using exbin as my personal pastebin, and I love it so far. However, I noticed that the environmental variable for setting ephemeral snippets is saying "Ephemeral age of snippets in seconds.", while in reality it is in minutes. This was quite confusing, because I set it to 3600 seconds (1 hour), but then 3600 seconds later it did not get deleted. not even after a day. Also, the countdown display (on the right side when viewing the snippet) display negative hours after 12 hours passed.
Once I recreated everything (database and container) from scratch, set the ephemeral variable to 60 (so 1 hour), the snippet got deleted perfectly. I now set it to 24, but the countdown timer on the side still is hardcoded to only 12 hours.

So these are 2 issues basically:
1. Documentation should be updated that ephemeral  the variable is in minutes, not seconds.
2. The countdown timer on the right side for the ephemeral snippet should reflect the correct time left, and not always starting from 12.

Neither of these are urgent or critical (maybe the documentation would be nice for others), so no pressure or anything :)

Otherwise love the app, it's awesome, especially the netcat support :)

**Comment by m1dnight** [comment]
Hopefully this weekend I will have some time on my hands to get at it. Once it's fixed I'll report back.

Thanks a lot for reporting!

**Comment by Vogete** [comment]
No rush on it! :)
Thanks! :)

**Comment by m1dnight** [comment]
I fixed the label. Now it will show the time in hours or minutes. 
Since the scrubber only runs every 10 minutes it will now show "0 minutes" if the scrubber hasn't passed yet. 

https://github.com/m1dnight/exbin/commit/88f4b30e178c2a942d8d5c0c213cc1ee29113ed9
