### ISSUE TITLE
Add documentation for API

### ISSUE THREAD

**Issue by joshproehl** [m1dnight/exbin#41]
Should have documentation for what API routes are available and how to access them.

Should document why/how the API_KEY env variable is used

Also, API_KEY appears to be required, Config.Reader throws an error if it is not there, even though README says it is optional.

**Comment by m1dnight** [comment]
I added some documentation in the README, but that seems like a cop-out. What do you suggest? 

https://github.com/m1dnight/exbin/commit/ffa5361f42d768131c02ee0e7c1df2bd33ca08d5

**Comment by joshproehl** [comment]
I think that looks great, considering the API is rather simple. :-) 

The only thing I'd add is a list of the available routes and expected parameters. (Which I think is really just adding an example of the show route?)

**Comment by m1dnight** [comment]
Done as well! I did not go the route of swagger because i dont have time, and the api is literally two endpoints.
