### ISSUE TITLE
Generating Secret Hash

### ISSUE THREAD

**Issue by jordantrizz** [m1dnight/exbin#54]
What's the best way to generate the secret hash for SECRET_KEY_BASE and SECRET_SALT without standing up the phoenix environment?

**Comment by m1dnight** [comment]
You can generate any random string I believe. 

The code apparently generates a 32 character string, but you can generate your own in bash using, for example, this command: 

`openssl rand 64 | openssl enc -A -base64`

**Comment by jordantrizz** [comment]
In the back of my mind, I thought it was simply a 64-character string that was required. But I thought I'd follow the README.md as I'm unfamiliar with phoenix/elixir. It might be good to update the README.md?

**Comment by m1dnight** [comment]
Done! Thanks for letting me know!
