### ISSUE TITLE
Unable to use Postmark as SMTP with TLS

### ISSUE THREAD

**Issue by jordantrizz** [m1dnight/exbin#57]
Using the following configuration

```
SMTP_RELAY="smtp.postmarkapp.com"
SMTP_PORT="587"
SMTP_USER="<redacted>"
SMTP_PASSWORD="<redacted>"
SMTP_FROM="<redacted>"
```

```
exbin    | 09:10:47.983 request_id=F2A-7GQjFQmu0NcAAAAR [warn] Description: 'Authenticity is not established by certificate path validation'
exbin    |      Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
```

**Comment by m1dnight** [comment]
Sorry for the late reply.

I have fixed this in the meanwhile while I'm renovating this project a bit. 

I have tried postmark myself, and it all works fine. 

The config has been changed, and now you can define it as you see fit. See the default config for instructions.
